### ISSUE TITLE
Timelock in the Vault contract

### ISSUE THREAD

**Issue by Brunya** [zgendao/utopia-fund#2]
When an user deposit fund into Vault it will be locked.
Locking period is specified in the Vault contract.
Owner address could change the locking period if necessary.
Change doesn't affect those already locked theirs fund.
Test period is 5min.

**Comment by TomiOhl** [comment]
Asd

**Comment by TomiOhl** [comment]
Already done in commit 484cc8b0a1208fb1b0bdea3ccec0b1f49aa1cb0d
The initial period was set to 60 min, but can be changed any time.
